CREATE DATABASE InformationRetrival;

USE InformationRetrival;

CREATE TABLE IF NOT EXISTS document
(
	ID					INT PRIMARY KEY,
    TITLE				VARCHAR(255),
    URL					VARCHAR(255),
    WORDCOUNT			LONG
);

CREATE TABLE IF NOT EXISTS terms
(
	WORD				VARCHAR(255) PRIMARY KEY,
    IDF					DOUBLE,
    LENGTH				INT
);

CREATE TABLE IF NOT EXISTS doc_terms
(
	ID					INT,
    WORD				VARCHAR(255),
    TF					DOUBLE,
    PRIMARY KEY(ID,WORD,TF),
    CONSTRAINT FOREIGN KEY (ID) REFERENCES document(ID),
    CONSTRAINT FOREIGN KEY (WORD) REFERENCES terms(WORD)
);

