CREATE DATABASE InformationRetrival;

USE InformationRetrival;

CREATE TABLE IF NOT EXISTS document
(
	ID					INT PRIMARY KEY,
    TITLE				VARCHAR(255),
    URL					VARCHAR(255),
    WORDCOUNT			LONG
);

CREATE TABLE IF NOT EXISTS term
(
	CONTENT				VARCHAR(255) PRIMARY KEY,
    IDF					DOUBLE,
    LENGTH				INT
);

CREATE TABLE IF NOT EXISTS doc_term
(
	ID					INT,
    CONTENT				VARCHAR(255),
    TF					INT,
    OFFSET				LONG,
    PRIMARY KEY(ID,CONTENT,TF),
    CONSTRAINT FOREIGN KEY (ID) REFERENCES document(ID),
    CONSTRAINT FOREIGN KEY (CONTENT) REFERENCES term(CONTENT)
)